<?php
namespace Motan\Protocol;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:03.
 */
class HeaderTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Header
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new Header;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Protocol\Header::buildHeaderBuf
     * @todo   Implement testBuildHeaderBuf().
     */
    public function testBuildHeaderBuf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setVersion
     * @todo   Implement testSetVersion().
     */
    public function testSetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setHeartbeat
     * @todo   Implement testSetHeartbeat().
     */
    public function testSetHeartbeat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::isHeartbeat
     * @todo   Implement testIsHeartbeat().
     */
    public function testIsHeartbeat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setGzip
     * @todo   Implement testSetGzip().
     */
    public function testSetGzip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::isGzip
     * @todo   Implement testIsGzip().
     */
    public function testIsGzip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setOneWay
     * @todo   Implement testSetOneWay().
     */
    public function testSetOneWay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::isOneWay
     * @todo   Implement testIsOneWay().
     */
    public function testIsOneWay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setProxy
     * @todo   Implement testSetProxy().
     */
    public function testSetProxy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::isProxy
     * @todo   Implement testIsProxy().
     */
    public function testIsProxy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setRequest
     * @todo   Implement testSetRequest().
     */
    public function testSetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::isRequest
     * @todo   Implement testIsRequest().
     */
    public function testIsRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::setSerialize
     * @todo   Implement testSetSerialize().
     */
    public function testSetSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::getSerialize
     * @todo   Implement testGetSerialize().
     */
    public function testGetSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Header::getRequestId
     * @todo   Implement testGetRequestId().
     */
    public function testGetRequestId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
