<?php
namespace Motan\Protocol;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:03.
 */
class MotanTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Motan
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new Motan;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Protocol\Motan::buildRequestHeader
     * @todo   Implement testBuildRequestHeader().
     */
    public function testBuildRequestHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::buildResponseHeader
     * @todo   Implement testBuildResponseHeader().
     */
    public function testBuildResponseHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::encode
     * @todo   Implement testEncode().
     */
    public function testEncode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::decode
     * @todo   Implement testDecode().
     */
    public function testDecode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::getBuffer
     * @todo   Implement testGetBuffer().
     */
    public function testGetBuffer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::getMetaDataSize
     * @todo   Implement testGetMetaDataSize().
     */
    public function testGetMetaDataSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::getBodySize
     * @todo   Implement testGetBodySize().
     */
    public function testGetBodySize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Protocol\Motan::decodex
     * @todo   Implement testDecodex().
     */
    public function testDecodex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
