<?php
namespace Motan\Cluster;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:20.
 */
class HaStrategyTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var HaStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HaStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Cluster\HaStrategy::getEndpoint
     * @todo   Implement testGetEndpoint().
     */
    public function testGetEndpoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
