<?php
namespace Motan\Cluster;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:02.
 */
class LoadBalanceTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var LoadBalance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new LoadBalance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Cluster\LoadBalance::getNode
     * @todo   Implement testGetNode().
     */
    public function testGetNode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
