<?php
namespace Motan\Serialize;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:03.
 */
class MotanTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Motan
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new Motan;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\Serialize\Motan::motan_table_type
     * @todo   Implement testMotan_table_type().
     */
    public function testMotan_table_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::motan_number_type
     * @todo   Implement testMotan_number_type().
     */
    public function testMotan_number_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::serialize_buf
     * @todo   Implement testSerialize_buf().
     */
    public function testSerialize_buf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::serializeMulti
     * @todo   Implement testSerializeMulti().
     */
    public function testSerializeMulti()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::deserialize_buf
     * @todo   Implement testDeserialize_buf().
     */
    public function testDeserialize_buf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Serialize\Motan::deserialize
     * @todo   Implement testDeserialize().
     */
    public function testDeserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
