<?php
namespace Motan\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:22.
 */
class RangeTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Range
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Range;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Route\Range::getIdcByIp
     * @todo   Implement testGetIdcByIp().
     */
    public function testGetIdcByIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Route\Range::getAgentGroupByIp
     * @todo   Implement testGetAgentGroupByIp().
     */
    public function testGetAgentGroupByIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Route\Range::getAgentGroupByIdc
     * @todo   Implement testGetAgentGroupByIdc().
     */
    public function testGetAgentGroupByIdc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
