<?php
namespace Motan\Cluster\Ha;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:20.
 */
class FailoverTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Failover
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Failover;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Cluster\Ha\Failover::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
