<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:20.
 */
class ConstantsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Constants
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Constants;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
