<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:02.
 */
class ConstantsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Constants
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Constants;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstants()
    {
        $this->assertEquals(\Motan\Constants::DEFAULT_AGENT_PORT, 9981);
    }
}
