<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:02.
 */
class EndpointerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Endpointer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new Endpointer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Endpointer::setLoadBalance
     * @todo   Implement testSetLoadBalance().
     */
    public function testSetLoadBalance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::setConnection
     * @todo   Implement testSetConnection().
     */
    public function testSetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::doCall
     * @todo   Implement testDoCall().
     */
    public function testDoCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::do4Multi
     * @todo   Implement testDo4Multi().
     */
    public function testDo4Multi()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getMException
     * @todo   Implement testGetMException().
     */
    public function testGetMException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getMRs
     * @todo   Implement testGetMRs().
     */
    public function testGetMRs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getResponseHeader
     * @todo   Implement testGetResponseHeader().
     */
    public function testGetResponseHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getResponseException
     * @todo   Implement testGetResponseException().
     */
    public function testGetResponseException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getResponseMetadata
     * @todo   Implement testGetResponseMetadata().
     */
    public function testGetResponseMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpointer::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
