<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:21.
 */
class OldClientTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var OldClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OldClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\OldClient::getResponseHeader
     * @todo   Implement testGetResponseHeader().
     */
    public function testGetResponseHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\OldClient::getResponseException
     * @todo   Implement testGetResponseException().
     */
    public function testGetResponseException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\OldClient::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\OldClient::getClientHandler
     * @todo   Implement testGetClientHandler().
     */
    public function testGetClientHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\OldClient::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
