<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:03.
 */
class ResponseTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\Response::getException
     * @todo   Implement testGetException().
     */
    public function testGetException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Response::getRs
     * @todo   Implement testGetRs().
     */
    public function testGetRs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Response::getRawResp
     * @todo   Implement testGetRawResp().
     */
    public function testGetRawResp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
