<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:22.
 */
class RouterTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Router::setDefaultIdc
     * @todo   Implement testSetDefaultIdc().
     */
    public function testSetDefaultIdc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Router::setDefaultGroup
     * @todo   Implement testSetDefaultGroup().
     */
    public function testSetDefaultGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Router::getDefaultIdc
     * @todo   Implement testGetDefaultIdc().
     */
    public function testGetDefaultIdc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Router::getDefaultGroup
     * @todo   Implement testGetDefaultGroup().
     */
    public function testGetDefaultGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
