<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:04.
 */
class URLTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var URL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new URL("motan2://127.0.0.1:9981/com.weibo.HelloMTService?group=motan-demo-rpc");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\URL::getAppName
     * @todo   Implement testGetAppName().
     */
    public function testGetAppName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setAppName
     * @todo   Implement testSetAppName().
     */
    public function testSetAppName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getRawUrl
     * @todo   Implement testGetRawUrl().
     */
    public function testGetRawUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setRawUrl
     * @todo   Implement testSetRawUrl().
     */
    public function testSetRawUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getUrlType
     * @todo   Implement testGetUrlType().
     */
    public function testGetUrlType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setUrlType
     * @todo   Implement testSetUrlType().
     */
    public function testSetUrlType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getParams
     * @todo   Implement testGetParams().
     */
    public function testGetParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setParams
     * @todo   Implement testSetParams().
     */
    public function testSetParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getHeaders
     * @todo   Implement testGetHeaders().
     */
    public function testGetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setHeaders
     * @todo   Implement testSetHeaders().
     */
    public function testSetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getService
     * @todo   Implement testGetService().
     */
    public function testGetService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setService
     * @todo   Implement testSetService().
     */
    public function testSetService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setMethod
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getHttpMethod
     * @todo   Implement testGetHttpMethod().
     */
    public function testGetHttpMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setHttpMethod
     * @todo   Implement testSetHttpMethod().
     */
    public function testSetHttpMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getEndpoint
     * @todo   Implement testGetEndpoint().
     */
    public function testGetEndpoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setEndpoint
     * @todo   Implement testSetEndpoint().
     */
    public function testSetEndpoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setVersion
     * @todo   Implement testSetVersion().
     */
    public function testSetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getSerialization
     * @todo   Implement testGetSerialization().
     */
    public function testGetSerialization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setSerialization
     * @todo   Implement testSetSerialization().
     */
    public function testSetSerialization()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getGroup
     * @todo   Implement testGetGroup().
     */
    public function testGetGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setGroup
     * @todo   Implement testSetGroup().
     */
    public function testSetGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getRequestId
     * @todo   Implement testGetRequestId().
     */
    public function testGetRequestId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setRequestId
     * @todo   Implement testSetRequestId().
     */
    public function testSetRequestId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getCluster
     * @todo   Implement testGetCluster().
     */
    public function testGetCluster()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setCluster
     * @todo   Implement testSetCluster().
     */
    public function testSetCluster()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getLoadbalance
     * @todo   Implement testGetLoadbalance().
     */
    public function testGetLoadbalance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setLoadbalance
     * @todo   Implement testSetLoadbalance().
     */
    public function testSetLoadbalance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getHaStrategy
     * @todo   Implement testGetHaStrategy().
     */
    public function testGetHaStrategy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setHaStrategy
     * @todo   Implement testSetHaStrategy().
     */
    public function testSetHaStrategy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getProtocol
     * @todo   Implement testGetProtocol().
     */
    public function testGetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setProtocol
     * @todo   Implement testSetProtocol().
     */
    public function testSetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setPath
     * @todo   Implement testSetPath().
     */
    public function testSetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getHost
     * @todo   Implement testGetHost().
     */
    public function testGetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setHost
     * @todo   Implement testSetHost().
     */
    public function testSetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getPort
     * @todo   Implement testGetPort().
     */
    public function testGetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setPort
     * @todo   Implement testSetPort().
     */
    public function testSetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getConnectionTimeOut
     * @todo   Implement testGetConnectionTimeOut().
     */
    public function testGetConnectionTimeOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setConnectionTimeOut
     * @todo   Implement testSetConnectionTimeOut().
     */
    public function testSetConnectionTimeOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getReadTimeOut
     * @todo   Implement testGetReadTimeOut().
     */
    public function testGetReadTimeOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setReadTimeOut
     * @todo   Implement testSetReadTimeOut().
     */
    public function testSetReadTimeOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getReadBufferSize
     * @todo   Implement testGetReadBufferSize().
     */
    public function testGetReadBufferSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setReadBufferSize
     * @todo   Implement testSetReadBufferSize().
     */
    public function testSetReadBufferSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getWriteBufferSize
     * @todo   Implement testGetWriteBufferSize().
     */
    public function testGetWriteBufferSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setWriteBufferSize
     * @todo   Implement testSetWriteBufferSize().
     */
    public function testSetWriteBufferSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getRetryTimes
     * @todo   Implement testGetRetryTimes().
     */
    public function testGetRetryTimes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::setRetryTimes
     * @todo   Implement testSetRetryTimes().
     */
    public function testSetRetryTimes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::addParams
     * @todo   Implement testAddParams().
     */
    public function testAddParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::getRawReqObj
     * @todo   Implement testGetRawReqObj().
     */
    public function testGetRawReqObj()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\URL::addHeaders
     * @todo   Implement testAddHeaders().
     */
    public function testAddHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
