<?php
namespace Motan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:04.
 */
class UtilsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestSkipped('Just Skip this.');
        $this->object = new Utils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Utils::genRequestId
     * @todo   Implement testGenRequestId().
     */
    public function testGenRequestId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::getGroup
     * @todo   Implement testGetGroup().
     */
    public function testGetGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::is_assoc
     * @todo   Implement testIs_assoc().
     */
    public function testIs_assoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::get_bytes
     * @todo   Implement testGet_bytes().
     */
    public function testGet_bytes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::toStr
     * @todo   Implement testToStr().
     */
    public function testToStr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::crc32Hash
     * @todo   Implement testCrc32Hash().
     */
    public function testCrc32Hash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::isAgentAlive
     * @todo   Implement testIsAgentAlive().
     */
    public function testIsAgentAlive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::split2Int
     * @todo   Implement testSplit2Int().
     */
    public function testSplit2Int()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::bigInt2float
     * @todo   Implement testBigInt2float().
     */
    public function testBigInt2float()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::getSerializer
     * @todo   Implement testGetSerializer().
     */
    public function testGetSerializer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::getHa
     * @todo   Implement testGetHa().
     */
    public function testGetHa()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::getLB
     * @todo   Implement testGetLB().
     */
    public function testGetLB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::getEndPoint
     * @todo   Implement testGetEndPoint().
     */
    public function testGetEndPoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::GetAgentConf
     * @todo   Implement testGetAgentConf().
     */
    public function testGetAgentConf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::GetServiceConf
     * @todo   Implement testGetServiceConf().
     */
    public function testGetServiceConf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::encodeZigzag64
     * @todo   Implement testEncodeZigzag64().
     */
    public function testEncodeZigzag64()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::decodeZigzag64
     * @todo   Implement testDecodeZigzag64().
     */
    public function testDecodeZigzag64()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::divideInt64ToInt32
     * @todo   Implement testDivideInt64ToInt32().
     */
    public function testDivideInt64ToInt32()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::encodeVarint
     * @todo   Implement testEncodeVarint().
     */
    public function testEncodeVarint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::combineInt32ToInt64
     * @todo   Implement testCombineInt32ToInt64().
     */
    public function testCombineInt32ToInt64()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::decodeVarint
     * @todo   Implement testDecodeVarint().
     */
    public function testDecodeVarint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::encodeZigzagVarint
     * @todo   Implement testEncodeZigzagVarint().
     */
    public function testEncodeZigzagVarint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Utils::decodeZigzagVarint
     * @todo   Implement testDecodeZigzagVarint().
     */
    public function testDecodeZigzagVarint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
