<?php
namespace Motan\Cluster\LoadBalance;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:01.
 */
class RoundRobinTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var RoundRobin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\Cluster\LoadBalance\RoundRobin::onRefresh
     * @todo   Implement testOnRefresh().
     */
    public function testOnRefresh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Cluster\LoadBalance\RoundRobin::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Cluster\LoadBalance\RoundRobin::selectToHolder
     * @todo   Implement testSelectToHolder().
     */
    public function testSelectToHolder()
    {
         // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
