<?php
namespace Motan\Endpoint;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:02.
 */
class GrpcTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Grpc
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\Endpoint\Grpc::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Endpoint\Grpc::multiCall
     * @todo   Implement testMultiCall().
     */
    public function testMultiCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
