<?php
namespace Motan\Resty;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-07-03 at 06:09:21.
 */
class ClientTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Client;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Motan\Resty\Client::addHeader
     * @todo   Implement testAddHeader().
     */
    public function testAddHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Resty\Client::addCookie
     * @todo   Implement testAddCookie().
     */
    public function testAddCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Resty\Client::addP
     * @todo   Implement testAddP().
     */
    public function testAddP()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Resty\Client::restyCall
     * @todo   Implement testRestyCall().
     */
    public function testRestyCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Resty\Client::getMotanClient
     * @todo   Implement testGetMotanClient().
     */
    public function testGetMotanClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
