<?php
namespace Motan\Transport;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-09 at 00:43:04.
 */
class ConnectionTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() : void
    {
        $this->markTestSkipped('Just Skip this.');
	    $url_obj = new \Motan\Url("motan2://127.0.0.1:9981/com.weibo.HelloMTService?group=motan-demo-rpc");
        $this->object = new Connection($url_obj);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() : void
    {
    }

    /**
     * @covers Motan\Transport\Connection::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Transport\Connection::buildConnection
     * @todo   Implement testBuildConnection().
     */
    public function testBuildConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Transport\Connection::write
     * @todo   Implement testWrite().
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Transport\Connection::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Motan\Transport\Connection::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
